### ISSUE TITLE
Beacon light not properly aligned[BUG] 

### ISSUE THREAD

**Issue by kevinwellsjr1** [Project-Mega-Pack/amp-aircraft-a321#14]
Bottom beacon light of off the beacon, and top beacon light appears to be a tiny bit taller than actual beacon. Attached in a GIF showing the bottom beacon didnt get one of top as its not really noticeable unless you zoom in
https://gyazo.com/c4959d5ccac8faeb840dfcc59197d36f?token=b18c1af6e6638ddeb2d1637cb6d889d0

**Comment by Clink1234** [comment]
There is also a bug with some strobes not working. All of this needs to be fixed.

**Comment by DEJHUR** [comment]
Hello hey I'm working on the light fix :)

**Comment by Clink1234** [comment]
Resolved in 2.4
