### ISSUE TITLE
Non-operational aircraft

### ISSUE THREAD

**Issue by adrianotrentim** [Project-Mega-Pack/amp-aircraft-a321#17]
When I turn on the external power and the batteries, all the panels (upper, lower) light up. MFD and MCU, ECAS are off
![1](https://user-images.githubusercontent.com/10145110/109492764-376dd900-7a6a-11eb-82ed-3d898f80a1e0.png)
![2](https://user-images.githubusercontent.com/10145110/109492808-45bbf500-7a6a-11eb-96bb-79eaed60b43c.png)
![3](https://user-images.githubusercontent.com/10145110/109492818-4ce30300-7a6a-11eb-8959-b71c06034aab.png)

**Comment by ghosh9691** [comment]
@adrianotrentim, Do you have the A32NX mod installed? It seems that this mod and the A32NX cannot co-exist in the Community folder at the same time. Remove that folder (the A32NX folder) and try again. That is what worked for me.

**Comment by Clink1234** [comment]
not compatible with a32nx
